fix(docker): reverting default containers to java 11
spinnaker/igor pull request #1168
Opened 2023-09-14 18:11 UTC by nemesisOsorio

Partially reverting https://github.com/spinnaker/igor/pull/1143

Fixes spinnaker/spinnaker#6879

2023-09-14 18:15 UTC, nemesisOsorio commented
@dbyron-sf @mattgogerly can you please take a look?

2023-09-14 18:16 UTC, dbyron-sf commented
Really hoping we hear from @mattgogerly before merging this....or perhaps someone else has tried to fix the issue?

2023-09-14 18:19 UTC, nemesisOsorio commented
> Really hoping we hear from @mattgogerly before merging this....or perhaps someone else has tried to fix the issue?

I believe we need to move completely to Java 17 to fix the issue and remove docker builds for Java 11

2023-09-14 18:21 UTC, dbyron-sf commented
> > Really hoping we hear from @mattgogerly before merging this....or perhaps someone else has tried to fix the issue?
> 
> I believe we need to move completely to Java 17 to fix the issue and remove docker builds for Java 11

If that's true (and it totally could be, I haven't looked into it), that's a pretty big change to the plan in https://github.com/spinnaker/governance/blob/master/rfc/java17.md, yes?

2023-09-14 18:25 UTC, nemesisOsorio commented
> > > Really hoping we hear from @mattgogerly before merging this....or perhaps someone else has tried to fix the issue?
> > 
> > 
> > I believe we need to move completely to Java 17 to fix the issue and remove docker builds for Java 11
> 
> If that's true (and it totally could be, I haven't looked into it), that's a pretty big change to the plan in https://github.com/spinnaker/governance/blob/master/rfc/java17.md, yes?

yes, it is a big change, I already tried running igor with Java 17

2023-09-15 17:34 UTC, dbyron-sf requested changes
@mattgogerly is back Monday and I believe has a smaller fix that allows us to keep java 17.  Let's hold off til we hear from him.

2023-09-18 15:45 UTC, dbyron-sf commented
handled by https://github.com/spinnaker/igor/pull/1170

2023-09-18 15:45 UTC, closed without merging